# Setup
title:        AutoReign
tagline:      Automate your world-conquering
baseurl:      "autorn"
paginate:     1

# About/contact
author:
  name:       Adam Keenan
  url:        http://adam-keenan.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
